package com.example.demo.dao;

import com.example.demo.DataObject.user1;

public interface user1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int insert(user1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int insertSelective(user1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    user1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(user1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int updateByPrimaryKey(user1 record);
}