package com.example.demo.dao;

import com.example.demo.DataObject.User;
import com.example.demo.service.model.UserModel;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     * @param record
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    User selectByPrimaryKey(Integer id);

    User selectByTelephone(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    int updateByPrimaryKey(User record);
}