package com.example.demo.DataObject;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spxx.id
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spxx.product_name
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spxx.img
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spxx.bewrite
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    private String bewrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spxx.price
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spxx.stock
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spxx.sales
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    private Integer sales;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spxx.id
     *
     * @return the value of spxx.id
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spxx.id
     *
     * @param id the value for spxx.id
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spxx.product_name
     *
     * @return the value of spxx.product_name
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spxx.product_name
     *
     * @param productName the value for spxx.product_name
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spxx.img
     *
     * @return the value of spxx.img
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spxx.img
     *
     * @param img the value for spxx.img
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spxx.bewrite
     *
     * @return the value of spxx.bewrite
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public String getBewrite() {
        return bewrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spxx.bewrite
     *
     * @param bewrite the value for spxx.bewrite
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public void setBewrite(String bewrite) {
        this.bewrite = bewrite == null ? null : bewrite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spxx.price
     *
     * @return the value of spxx.price
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spxx.price
     *
     * @param price the value for spxx.price
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spxx.stock
     *
     * @return the value of spxx.stock
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spxx.stock
     *
     * @param stock the value for spxx.stock
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spxx.sales
     *
     * @return the value of spxx.sales
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spxx.sales
     *
     * @param sales the value for spxx.sales
     *
     * @mbg.generated Sun Aug 08 22:26:26 GMT+08:00 2021
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }
}