package com.example.demo.DataObject;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddxx.id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddxx.user_id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddxx.commodity_id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    private Integer commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddxx.commodity_price
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    private Double commodityPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddxx.amount
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddxx.total_price
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    private Double totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddxx.id
     *
     * @return the value of ddxx.id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddxx.id
     *
     * @param id the value for ddxx.id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddxx.user_id
     *
     * @return the value of ddxx.user_id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddxx.user_id
     *
     * @param userId the value for ddxx.user_id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddxx.commodity_id
     *
     * @return the value of ddxx.commodity_id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddxx.commodity_id
     *
     * @param commodityId the value for ddxx.commodity_id
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddxx.commodity_price
     *
     * @return the value of ddxx.commodity_price
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public Double getCommodityPrice() {
        return commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddxx.commodity_price
     *
     * @param commodityPrice the value for ddxx.commodity_price
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public void setCommodityPrice(Double commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddxx.amount
     *
     * @return the value of ddxx.amount
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddxx.amount
     *
     * @param amount the value for ddxx.amount
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddxx.total_price
     *
     * @return the value of ddxx.total_price
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddxx.total_price
     *
     * @param totalPrice the value for ddxx.total_price
     *
     * @mbg.generated Tue Aug 10 23:38:55 GMT+08:00 2021
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
}