package com.example.demo.DataObject;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.id
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.name
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.age
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.telephone
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.password
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.id
     *
     * @return the value of user1.id
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.id
     *
     * @param id the value for user1.id
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.name
     *
     * @return the value of user1.name
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.name
     *
     * @param name the value for user1.name
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.age
     *
     * @return the value of user1.age
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.age
     *
     * @param age the value for user1.age
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.telephone
     *
     * @return the value of user1.telephone
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.telephone
     *
     * @param telephone the value for user1.telephone
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.password
     *
     * @return the value of user1.password
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.password
     *
     * @param password the value for user1.password
     *
     * @mbg.generated Sat Aug 07 01:06:02 GMT+08:00 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}